services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs2025q2-service-app
    container_name: music_service_app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    networks:
      - music_service_network
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: music_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - music_service_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  music_service_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
